const DATA = [
    {
        "Region": "Arica y Parinacota",
        "Casos totales acumulados": "74799",
        "Fallecidos confirmados totales": "727",
        "Fallecidos sospechosos probables u otros totales": "144",
        "Fallecidos totales": "871",
        "Casos confirmados recuperados": "73467",
        "Casos confirmados por antigeno": "22035",
        "Casos con sospecha de reinfeccion": "1220",
        "Casos probables acumulados": "3442",
        "Casos activos probables": "0",
        "Casos nuevos totales": "59",
        "Casos nuevos con sintomas": "30",
        "Casos nuevos sin sintomas*": "25",
        "Casos nuevos reportados por laboratorio": "4",
        "Casos nuevos confirmados por antigeno": "42",
        "Casos activos confirmados": "192"
    },
    {
        "Region": "Tarapac\u00e1",
        "Casos totales acumulados": "105844",
        "Fallecidos confirmados totales": "1032",
        "Fallecidos sospechosos probables u otros totales": "119",
        "Fallecidos totales": "1151",
        "Casos confirmados recuperados": "104191",
        "Casos confirmados por antigeno": "23589",
        "Casos con sospecha de reinfeccion": "686",
        "Casos probables acumulados": "10390",
        "Casos activos probables": "0",
        "Casos nuevos totales": "67",
        "Casos nuevos con sintomas": "40",
        "Casos nuevos sin sintomas*": "2",
        "Casos nuevos reportados por laboratorio": "25",
        "Casos nuevos confirmados por antigeno": "52",
        "Casos activos confirmados": "241"
    },
    {
        "Region": "Antofagasta",
        "Casos totales acumulados": "172822",
        "Fallecidos confirmados totales": "1612",
        "Fallecidos sospechosos probables u otros totales": "298",
        "Fallecidos totales": "1910",
        "Casos confirmados recuperados": "170000",
        "Casos confirmados por antigeno": "27598",
        "Casos con sospecha de reinfeccion": "1723",
        "Casos probables acumulados": "6821",
        "Casos activos probables": "0",
        "Casos nuevos totales": "137",
        "Casos nuevos con sintomas": "67",
        "Casos nuevos sin sintomas*": "17",
        "Casos nuevos reportados por laboratorio": "53",
        "Casos nuevos confirmados por antigeno": "55",
        "Casos activos confirmados": "486"
    },
    {
        "Region": "Atacama",
        "Casos totales acumulados": "107223",
        "Fallecidos confirmados totales": "572",
        "Fallecidos sospechosos probables u otros totales": "117",
        "Fallecidos totales": "689",
        "Casos confirmados recuperados": "105907",
        "Casos confirmados por antigeno": "43032",
        "Casos con sospecha de reinfeccion": "1022",
        "Casos probables acumulados": "1741",
        "Casos activos probables": "0",
        "Casos nuevos totales": "91",
        "Casos nuevos con sintomas": "32",
        "Casos nuevos sin sintomas*": "21",
        "Casos nuevos reportados por laboratorio": "38",
        "Casos nuevos confirmados por antigeno": "70",
        "Casos activos confirmados": "408"
    },
    {
        "Region": "Coquimbo",
        "Casos totales acumulados": "197076",
        "Fallecidos confirmados totales": "1576",
        "Fallecidos sospechosos probables u otros totales": "298",
        "Fallecidos totales": "1874",
        "Casos confirmados recuperados": "194075",
        "Casos confirmados por antigeno": "53266",
        "Casos con sospecha de reinfeccion": "1386",
        "Casos probables acumulados": "9393",
        "Casos activos probables": "0",
        "Casos nuevos totales": "198",
        "Casos nuevos con sintomas": "131",
        "Casos nuevos sin sintomas*": "35",
        "Casos nuevos reportados por laboratorio": "32",
        "Casos nuevos confirmados por antigeno": "117",
        "Casos activos confirmados": "643"
    },
    {
        "Region": "Valpara\u00edso",
        "Casos totales acumulados": "461950",
        "Fallecidos confirmados totales": "5012",
        "Fallecidos sospechosos probables u otros totales": "1231",
        "Fallecidos totales": "6243",
        "Casos confirmados recuperados": "452897",
        "Casos confirmados por antigeno": "125129",
        "Casos con sospecha de reinfeccion": "2395",
        "Casos probables acumulados": "50200",
        "Casos activos probables": "0",
        "Casos nuevos totales": "556",
        "Casos nuevos con sintomas": "296",
        "Casos nuevos sin sintomas*": "68",
        "Casos nuevos reportados por laboratorio": "192",
        "Casos nuevos confirmados por antigeno": "315",
        "Casos activos confirmados": "1603"
    },
    {
        "Region": "Metropolitana",
        "Casos totales acumulados": "1864595",
        "Fallecidos confirmados totales": "23994",
        "Fallecidos sospechosos probables u otros totales": "6181",
        "Fallecidos totales": "30175",
        "Casos confirmados recuperados": "1825701",
        "Casos confirmados por antigeno": "344879",
        "Casos con sospecha de reinfeccion": "21242",
        "Casos probables acumulados": "161591",
        "Casos activos probables": "0",
        "Casos nuevos totales": "1269",
        "Casos nuevos con sintomas": "646",
        "Casos nuevos sin sintomas*": "107",
        "Casos nuevos reportados por laboratorio": "516",
        "Casos nuevos confirmados por antigeno": "601",
        "Casos activos confirmados": "4282"
    },
    {
        "Region": "O\u2019Higgins",
        "Casos totales acumulados": "209615",
        "Fallecidos confirmados totales": "2167",
        "Fallecidos sospechosos probables u otros totales": "576",
        "Fallecidos totales": "2743",
        "Casos confirmados recuperados": "205749",
        "Casos confirmados por antigeno": "62158",
        "Casos con sospecha de reinfeccion": "1094",
        "Casos probables acumulados": "14803",
        "Casos activos probables": "0",
        "Casos nuevos totales": "185",
        "Casos nuevos con sintomas": "107",
        "Casos nuevos sin sintomas*": "40",
        "Casos nuevos reportados por laboratorio": "38",
        "Casos nuevos confirmados por antigeno": "108",
        "Casos activos confirmados": "616"
    },
    {
        "Region": "Maule",
        "Casos totales acumulados": "330749",
        "Fallecidos confirmados totales": "2715",
        "Fallecidos sospechosos probables u otros totales": "507",
        "Fallecidos totales": "3222",
        "Casos confirmados recuperados": "325562",
        "Casos confirmados por antigeno": "100026",
        "Casos con sospecha de reinfeccion": "4042",
        "Casos probables acumulados": "10642",
        "Casos activos probables": "0",
        "Casos nuevos totales": "305",
        "Casos nuevos con sintomas": "159",
        "Casos nuevos sin sintomas*": "59",
        "Casos nuevos reportados por laboratorio": "87",
        "Casos nuevos confirmados por antigeno": "147",
        "Casos activos confirmados": "888"
    },
    {
        "Region": "\u00d1uble",
        "Casos totales acumulados": "148207",
        "Fallecidos confirmados totales": "1053",
        "Fallecidos sospechosos probables u otros totales": "197",
        "Fallecidos totales": "1250",
        "Casos confirmados recuperados": "145833",
        "Casos confirmados por antigeno": "48017",
        "Casos con sospecha de reinfeccion": "1147",
        "Casos probables acumulados": "10182",
        "Casos activos probables": "0",
        "Casos nuevos totales": "186",
        "Casos nuevos con sintomas": "104",
        "Casos nuevos sin sintomas*": "10",
        "Casos nuevos reportados por laboratorio": "72",
        "Casos nuevos confirmados por antigeno": "97",
        "Casos activos confirmados": "557"
    },
    {
        "Region": "Biob\u00edo",
        "Casos totales acumulados": "483856",
        "Fallecidos confirmados totales": "3962",
        "Fallecidos sospechosos probables u otros totales": "688",
        "Fallecidos totales": "4650",
        "Casos confirmados recuperados": "476286",
        "Casos confirmados por antigeno": "106232",
        "Casos con sospecha de reinfeccion": "2811",
        "Casos probables acumulados": "35892",
        "Casos activos probables": "0",
        "Casos nuevos totales": "407",
        "Casos nuevos con sintomas": "178",
        "Casos nuevos sin sintomas*": "77",
        "Casos nuevos reportados por laboratorio": "152",
        "Casos nuevos confirmados por antigeno": "178",
        "Casos activos confirmados": "1300"
    },
    {
        "Region": "Araucan\u00eda",
        "Casos totales acumulados": "281283",
        "Fallecidos confirmados totales": "2218",
        "Fallecidos sospechosos probables u otros totales": "580",
        "Fallecidos totales": "2798",
        "Casos confirmados recuperados": "276926",
        "Casos confirmados por antigeno": "51094",
        "Casos con sospecha de reinfeccion": "3879",
        "Casos probables acumulados": "11320",
        "Casos activos probables": "0",
        "Casos nuevos totales": "196",
        "Casos nuevos con sintomas": "85",
        "Casos nuevos sin sintomas*": "23",
        "Casos nuevos reportados por laboratorio": "88",
        "Casos nuevos confirmados por antigeno": "71",
        "Casos activos confirmados": "569"
    },
    {
        "Region": "Los R\u00edos",
        "Casos totales acumulados": "139665",
        "Fallecidos confirmados totales": "1119",
        "Fallecidos sospechosos probables u otros totales": "232",
        "Fallecidos totales": "1351",
        "Casos confirmados recuperados": "137218",
        "Casos confirmados por antigeno": "39085",
        "Casos con sospecha de reinfeccion": "1315",
        "Casos probables acumulados": "6035",
        "Casos activos probables": "0",
        "Casos nuevos totales": "155",
        "Casos nuevos con sintomas": "87",
        "Casos nuevos sin sintomas*": "40",
        "Casos nuevos reportados por laboratorio": "28",
        "Casos nuevos confirmados por antigeno": "109",
        "Casos activos confirmados": "501"
    },
    {
        "Region": "Los Lagos",
        "Casos totales acumulados": "233439",
        "Fallecidos confirmados totales": "2104",
        "Fallecidos sospechosos probables u otros totales": "376",
        "Fallecidos totales": "2480",
        "Casos confirmados recuperados": "229462",
        "Casos confirmados por antigeno": "34831",
        "Casos con sospecha de reinfeccion": "3896",
        "Casos probables acumulados": "16331",
        "Casos activos probables": "0",
        "Casos nuevos totales": "173",
        "Casos nuevos con sintomas": "68",
        "Casos nuevos sin sintomas*": "19",
        "Casos nuevos reportados por laboratorio": "86",
        "Casos nuevos confirmados por antigeno": "58",
        "Casos activos confirmados": "544"
    },
    {
        "Region": "Ays\u00e9n",
        "Casos totales acumulados": "33957",
        "Fallecidos confirmados totales": "182",
        "Fallecidos sospechosos probables u otros totales": "27",
        "Fallecidos totales": "209",
        "Casos confirmados recuperados": "33524",
        "Casos confirmados por antigeno": "12653",
        "Casos con sospecha de reinfeccion": "1673",
        "Casos probables acumulados": "1794",
        "Casos activos probables": "0",
        "Casos nuevos totales": "36",
        "Casos nuevos con sintomas": "22",
        "Casos nuevos sin sintomas*": "10",
        "Casos nuevos reportados por laboratorio": "4",
        "Casos nuevos confirmados por antigeno": "27",
        "Casos activos confirmados": "102"
    },
    {
        "Region": "Magallanes",
        "Casos totales acumulados": "64756",
        "Fallecidos confirmados totales": "654",
        "Fallecidos sospechosos probables u otros totales": "105",
        "Fallecidos totales": "759",
        "Casos confirmados recuperados": "63562",
        "Casos confirmados por antigeno": "10119",
        "Casos con sospecha de reinfeccion": "2156",
        "Casos probables acumulados": "3290",
        "Casos activos probables": "0",
        "Casos nuevos totales": "57",
        "Casos nuevos con sintomas": "28",
        "Casos nuevos sin sintomas*": "0",
        "Casos nuevos reportados por laboratorio": "29",
        "Casos nuevos confirmados por antigeno": "22",
        "Casos activos confirmados": "141"
    },
    {
        "Region": "Se desconoce regi\u00f3n de origen",
        "Casos totales acumulados": "42",
        "Fallecidos confirmados totales": "0",
        "Fallecidos sospechosos probables u otros totales": "2",
        "Fallecidos totales": "2",
        "Casos confirmados recuperados": "41",
        "Casos confirmados por antigeno": "0",
        "Casos con sospecha de reinfeccion": "0",
        "Casos probables acumulados": "0",
        "Casos activos probables": "0",
        "Casos nuevos totales": "0",
        "Casos nuevos con sintomas": "0",
        "Casos nuevos sin sintomas*": "0",
        "Casos nuevos reportados por laboratorio": "0",
        "Casos nuevos confirmados por antigeno": "0",
        "Casos activos confirmados": "0"
    },
    {
        "Region": "Total",
        "Casos totales acumulados": "4909878",
        "Fallecidos confirmados totales": "50699",
        "Fallecidos sospechosos probables u otros totales": "11678",
        "Fallecidos totales": "62377",
        "Casos confirmados recuperados": "4820401",
        "Casos confirmados por antigeno": "1103743",
        "Casos con sospecha de reinfeccion": "51687",
        "Casos probables acumulados": "353867",
        "Casos activos probables": "0",
        "Casos nuevos totales": "4077",
        "Casos nuevos con sintomas": "2080",
        "Casos nuevos sin sintomas*": "553",
        "Casos nuevos reportados por laboratorio": "1444",
        "Casos nuevos confirmados por antigeno": "2069",
        "Casos activos confirmados": "13073"
    }
]